
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 2147483647
	#The name of the modpack
	modpackName = "PolyMC"
	#The version of the modpack
	modpackVersion = "v1.2.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

